### ISSUE TITLE
Journal doesn't split

### ISSUE THREAD

**Issue by vt-tom** [toastygm/split-join-journal#1]
System: Das schwarze Auge/The Dark Eye 5th Edition - v10 Beta
Foundry: v10 testing 3

I tried to split a journal with several h1 headers but it doenst split the journal:
![grafik](https://user-images.githubusercontent.com/80099175/184208952-1fd0aef8-5f0c-43b4-8373-af4366e22852.png)

**Comment by toastygm** [comment]
In the example you gave:

1. The Journal Page named "Journal Page Title" should have been split into 4 new Journal pages (the pages named "Header 1", "Header 2", "Header 3", and "Header 4") and these pages placed in a new Journal named "Journal Page Title".

2. The Journal "Split Journal Test", when split, should have created a new folder named "Split Journal Test" with 4 new Journals in it named "Header 1", "Header 2", "Header 3", and "Header 4".  Each of those journals should have only one page.

Is this what you are seeing?  If not, can you please be specific about how to reproduce your problem.

**Comment by vt-tom** [comment]
I split the Journal "Split Journal Test" with Header 1-4 (all h1) with the module. The result was the Folder "Split Journal Test" and the Journal Note: "Journal Page Title"

The folder was as expected but into it should have been 4 journals with the Title Header 1, Header 2 ,Header 3 and Header 4.

**Comment by toastygm** [comment]
You are not being clear.

Did you split a journal with one page, or multiple pages?

Be aware that if you split a JOURNAL, then it creates a folder with one Journal for each PAGE in the original Journal.  **It does not split by header, because new journals don't have headers!** Only Pages have headers.

If you split a PAGE, then it will ask which header to split on, and it will create new PAGES based on that.

So, so far your problem doesn't seem like a real problem.

**Comment by toastygm** [comment]
Try this:

1. Create a new journal, called "Test Journal".
2. Create three pages in this journal, named "Page One", "Page Two", and "Page Three".
3. For "Page Two", put in the following text source:
```
<h1>The Good</h1>
This is a story about a good person.
<h1>The Bad</h1>
This is a story about a bad person.
<h1>The Ugly</h1>
This is a story about an ugly person
```
4. Right click on page 2, then select "Split Page".  Split based on Heading 1.  It should create a new Journal named "Page Two" containing three pages: The Good, The Bad, and The Ugly.

This is how it is supposed to work.

**Comment by vt-tom** [comment]
Sorry my English is not the best, I will try to explain better what I dit:

I created a new journal entry named "split journal test"

Then I created a journal page named "journal page title"

In this journal page I declared 4 headers with the stile h1
Header 1
Header 2
Header 3
Header 4

My expectation was, that split journal would split this single journal with one journal note into 4 journals with 1 journal note or 1 journal page with 4 journal notes

But as you can see in my Screenshot, split journal doesn't ask which header I want to split.

I hope this is better to unterstand?

But  I will try your solutions in the next day, maybe I am somehow misunderstanding something.

**Comment by vt-tom** [comment]
After sending my last comment I think I know what I misunderstood. I will test again and send you a reply the next days 😊

**Comment by toastygm** [comment]
Yes, now I understand.

The module does not work how you think it does.  Let me explain using your example.

You created Journal "Split Journal Test", with a single page named "Journal Page Title".  This page has 4 "Heading 1" entries in it.

If you want those entries split, then you have to right click on the page "Journal Page Title", and request it to split.  It will then create a new Journal named "Journal Page Title", with four pages in it.

However, if you click on the Journal "Split Journal Test" and select split, then all you will get will be a new folder containing  one Journal entry named "Journal Page Title".  That is because the Journal "Split Journal Test" has only one page.

None of this is recursive.  The only time it splits on Headings is when you split a Journal **Page**.  Splitting a Journal splits all of the pages out into separate journals.  This is not very useful if your journal has only one page.

**Comment by vt-tom** [comment]
This is so logical that I am a little bit ashamed not trying this myself...

Thanks for the explanation and keep going. I really like your module. It helps me so much creating my adventure content.

**Comment by vt-tom** [comment]
I have tested it and it works like a charm. Thank you for your patience and keep going.

**Comment by vt-tom** [comment]
Close because im stupid :)
